[package]
name = "sitelen-ilo"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
nom.workspace = true
nom_locate.workspace = true

sitelen-ilo-macros.workspace = true
