[package]
name = "sitelen-ilo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
env_logger = "0.11.8"
log = { version = "0.4.28", features = ["std"] }
nom = "8.0.0"
